### ISSUE TITLE
Has should return true when passed an empty slice

### ISSUE THREAD

**Issue by abursavich** [fatih/set#25]
Has is equivalent to IsSuperset and all sets are supersets of the empty set, but both implementations of Has look like:

``` go
func (s *set) Has(items ...interface{}) bool {
    if len(items) == 0 {
        return false
    }
    // ...
}
```

**Comment by fatih** [comment]
I'm closing this project and archiving it. Thanks all. For more info: https://github.com/fatih/set/tree/v0.1.1#archived-project-no-maintenance
