### ISSUE TITLE
unclear whether i should use non thread safe set instead of thread safe

### ISSUE THREAD

**Issue by oryband** [fatih/set#27]
Can you please elaborate and add it to the README and godoc?

**Comment by fatih** [comment]
I think it's very clear. Using thread safe set, you comprise performance (because of mutex overhead). With the non thread safe you don't have that.

**Comment by oryband** [comment]
After digging around a bit, i found #7 . In addition that's the reason I thought there are two versions of the set. However, I still think a small sentences e.g. "Thread-safe performance can be slower than non-thread-safe" could help some. Feel free to close unfixed if you feel I'm wrong, that's fine.

**Comment by fatih** [comment]
I'm closing this project and archiving it. Thanks all. For more info: https://github.com/fatih/set/tree/v0.1.1#archived-project-no-maintenance
