### ISSUE TITLE
Missing docstring for Separate()

### ISSUE THREAD

**Issue by uovobw** [fatih/set#28]
Hi,
thanks for the awesome struct, it's very very useful!
Using it i noticed that there is a missing docstring [here](https://github.com/fatih/set/blob/v0.1.1/set_nots.go#L193) leaving an eerie 

`// Separate removes the set items containing in t from set s. Please aware that` 

that bodes doom.

**Comment by sdboyer** [comment]
LOL. That does rather feel like ![yikes](http://vignette3.wikia.nocookie.net/lovecraft/images/9/95/5b1d071c622d3bb26b6c26a80d80534e.jpg/revision/latest?cb=20140818055502)

i think i wrote the original incomplete sentence. if i can remember what that warning was supposed to be, i'll put up a PR...

**Comment by fatih** [comment]
I'm closing this project and archiving it. Thanks all. For more info: https://github.com/fatih/set/tree/v0.1.1#archived-project-no-maintenance
