### ISSUE TITLE
Add a method to create a new set from an already existing array

### ISSUE THREAD

**Issue by lstep** [fatih/set#29]
Add a method to create a new set from an already existing array.

```
l := []string{"foo", "bar"}
s := set.New(l)
```

Trying with the variadic operator (`set.New(l...)`) doesn't work either. Do I need to make loop to add them individually?

**Comment by RayfenWindspear** [comment]
The internal structure for Sets in this package is a map, not an array. So yes, you would need to loop. Though it would be simple enough to add a method that does it for you anyway.

**Comment by fatih** [comment]
I'm closing this project and archiving it. Thanks all. For more info: https://github.com/fatih/set/tree/v0.1.1#archived-project-no-maintenance
