### ISSUE TITLE
It would be great if set.Union can return SetNonTS or Set instances

### ISSUE THREAD

**Issue by rishiloyola** [fatih/set#37]
I have an array of sets and I want to find the union of all the sets. Rather then doing type cast it would be great if you can provide an inbuilt feature to return the SetNonTS or Set instance rather than an interface.

**Code:**
```go
unionSet := set.NewNonTS()  // find unique files across agents
for _, records := range Agents {  // iterate through agents(100 in size) and get files stored on them,
        agentSet := set.NewNonTS()   // Create set of those files
        for _, catalog := range records {
	      agentSet.Add(catalog.Path)  
	}
	unionSet = set.NewNonTS(set.Union(unionSet, agentSet))  // Needed Feature: unionSet = set.Union(unionSet, agentSet) just like array1 = append(array1, array2)
}
```

**Comment by fatih** [comment]
I'm closing this project and archiving it. Thanks all. For more info: https://github.com/fatih/set/tree/v0.1.1#archived-project-no-maintenance
